---
Name: checkoutconfig
---
## YML Config
Controller:
  extensions:
    - CheckoutControllerExtension
SiteConfig:
  extensions:
    - CheckoutSiteConfigExtension
Member:
  extensions:
    - CheckoutMemberExtension
Group:
  extensions:
    - CheckoutGroupExtension
